# Generated by Django 4.0.4 on 2022-05-19 02:24

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('gender', models.BinaryField(choices=[('f', 'Female'), ('m', 'Male')], default=('f', 'Female'))),
                ('birth', models.DateField(null=True)),
                ('death', models.DateField(null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2, null=True)),
            ],
            options={
                'ordering': ['authorId'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.IntegerField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=45)),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author')),
            ],
            options={
                'ordering': ['bookId'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['genreId'],
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('pressId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('readerId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('birth', models.DateField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordId', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('due', models.DateTimeField(null=True)),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('readerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='pressID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.press'),
        ),
        migrations.AddField(
            model_name='book',
            name='recordID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.record'),
        ),
    ]
