# Generated by Django 4.0.4 on 2022-05-20 14:07

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1)),
                ('birth', models.DateField(blank=True, null=True)),
                ('death', models.DateField(blank=True, null=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors')),
            ],
            options={
                'ordering': ['authorId'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books')),
                ('authorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author')),
            ],
            options={
                'ordering': ['bookId'],
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('binstanceId', models.AutoField(primary_key=True, serialize=False)),
                ('on_shelf', models.BinaryField(default=False, verbose_name=[(True, 'On shelf'), (False, 'Loan')])),
                ('position', models.CharField(max_length=45)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['genreId'],
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('pressId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('readerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('birth', models.DateField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordId', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('due', models.DateTimeField(null=True)),
                ('binstanceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bookinstance')),
                ('readerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genreId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='pressId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.press'),
        ),
        migrations.AddField(
            model_name='book',
            name='recordId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.record'),
        ),
    ]
