# Generated by Django 4.0.4 on 2022-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
