# Generated by Django 4.0.4 on 2022-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_press_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pressId',
            new_name='press',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='recordId',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='binstanceId',
            new_name='binstance',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='readerId',
            new_name='reader',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genreId',
        ),
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='record',
            name='recordId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
