# Generated by Django 4.0.4 on 2022-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_authorid_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='author.png', null=True, upload_to='authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='cover.jpg', null=True, upload_to='books'),
        ),
    ]
