# Generated by Django 4.0.4 on 2022-05-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_author_iamge_author_image_alter_author_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authorId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genreId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='press',
            name='pressId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reader',
            name='readerId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
