# Generated by Django 4.0.4 on 2022-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_image_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='Book', to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='author.png', upload_to='authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='cover.jpg', upload_to='books'),
        ),
    ]
