# Generated by Django 4.0.4 on 2022-05-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_authorid_alter_book_bookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.BinaryField(choices=[('f', 'Female'), ('m', 'Male')]),
        ),
    ]
