# Generated by Django 4.0.4 on 2022-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_genre_book_book_genre_alter_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='on_shelf',
            field=models.BooleanField(default=False, verbose_name=[(True, 'On shelf'), (False, 'Loan')]),
        ),
    ]
