# Generated by Django 4.0.4 on 2022-05-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.BinaryField(choices=[('f', 'Female'), ('m', 'Male')], editable=True),
        ),
    ]
