# Generated by Django 4.0.4 on 2022-05-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_on_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='on_shelf',
            field=models.BooleanField(default=False),
        ),
    ]
