# Generated by Django 4.0.4 on 2022-05-21 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_alter_bookinstance_on_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='on_shelf',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
