# Generated by Django 4.0.4 on 2022-05-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_on_shelf_alter_record_reader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='on_shelf',
        ),
        migrations.AddField(
            model_name='record',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
