# Generated by Django 4.0.4 on 2022-05-19 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_book_recordid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='recordID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.record'),
        ),
    ]
