# Generated by Django 4.0.4 on 2022-05-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_bookinstance_on_shelf_record_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='record',
        ),
    ]
