# Generated by Django 4.0.4 on 2022-05-19 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_book_recordid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authorID',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pressID',
        ),
        migrations.RemoveField(
            model_name='book',
            name='recordID',
        ),
        migrations.AddField(
            model_name='book',
            name='authorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genreId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='pressId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.press'),
        ),
        migrations.AddField(
            model_name='book',
            name='recordId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='bookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='record',
            name='readerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.reader'),
        ),
    ]
